### ISSUE TITLE
Monitor/unmonitor doesn't work for me

### ISSUE THREAD

**Issue by Rumbles** [polymeris/python-monit#2]
Using monit 5.6 on ubuntu 14.04 I can start/stop a process but trying to monitor/unmonitor, nothing changes on monit status.

Running via the monit daemon itself I can make the change but not via your tool.

I was trying to understand this myself but could not find any valid monit documentation that would help me understand the API, can you point me to the docs you used so I can try and understand the issue better myself, and hopefully send you a PR if I figure out the issue?

I have raised an issue with monit about their lack of documentation.

**Comment by polymeris** [comment]
Sorry, I can't remember what docs I used (this was years ago), or if I just reverse-engineered the endpoints.

**Comment by Rumbles** [comment]
Thanks for merging my PR @polymeris any chance you can push that to pip?

**Comment by polymeris** [comment]
I am looking into it. I haven't used much Python lately, and only now realized that they deprecated the old pypi, and are replacing it with a new one that requires a different upload procedure.

**Comment by polymeris** [comment]
Done. Sorry about the delay.
https://pypi.org/manage/project/monit/release/0.3/
